# Generated by Django 3.0.8 on 2020-07-27 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20200727_2026'),
        ('job_applications', '0002_auto_20200727_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='jobs.Job'),
        ),
    ]
