# Generated by Django 3.0.8 on 2020-07-28 18:30
from django.utils.text import slugify
from django.db import migrations

def slugify_companies(apps, schema_editor):
    Company = apps.get_model('companies', 'Company')
    for company in Company.objects.all():
        company.slug = slugify(company.name)
        company.save()



class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_company_slug'),
    ]

    operations = [
        migrations.RunPython(slugify_companies, migrations.RunPython.noop)
    ]
