# Generated by Django 3.0.8 on 2020-07-28 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_auto_20200728_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='no_employees',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
