# Generated by Django 3.0.8 on 2020-07-14 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20200711_1321'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ats_jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atsjob',
            name='category',
        ),
        migrations.AddField(
            model_name='atsjob',
            name='author_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='atsjob',
            name='category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='ats_jobs.Category'),
        ),
        migrations.AddField(
            model_name='atsjob',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ats_jobs', to='companies.Company'),
        ),
        migrations.AlterField(
            model_name='atsjob',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
