# Generated by Django 3.0.8 on 2020-07-14 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ats_jobs', '0002_auto_20200714_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='JobTag',
            fields=[
                ('tag_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ats_jobs.Tag')),
                ('AtsJob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ats_jobs', to='ats_jobs.AtsJob')),
            ],
            bases=('ats_jobs.tag',),
        ),
    ]
