# Generated by Django 3.0.8 on 2020-07-17 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats_jobs', '0003_jobtag_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='atsjob',
            name='tags',
            field=models.ManyToManyField(to='ats_jobs.Tag'),
        ),
    ]
