# Generated by Django 3.0.8 on 2020-07-17 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ats_jobs', '0004_atsjob_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atsjob',
            old_name='title',
            new_name='name',
        ),
    ]
