# Generated by Django 3.0.8 on 2020-07-17 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ats_jobs', '0005_auto_20200717_2140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atsjob',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='atsjob',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='atsjob',
            old_name='company_id',
            new_name='company',
        ),
    ]
